### ISSUE TITLE
When will the code be made public？

### ISSUE THREAD

**Issue by watertianyi** [Atif-Anwer/SpecSeg#1]

**Comment by Atif-Anwer** [comment]
Hi! 
The code is already in the repository. You can find it in the '[SpecSeg.ipynb](https://github.com/Atif-Anwer/SpecSeg/blob/main/SpecSeg.ipynb)' file. I intend to add a python script aswell for running locally, but im a bit bogged down with some other work. Its just the refactored jupyter notebook so should not be any different.

**Comment by watertianyi** [comment]
@Atif-Anwer You can post the weight of inference？

**Comment by Atif-Anwer** [comment]
Oh yeah, I just noticed they aren't in the repository for some reason. I'll do it today. Not sure why the push didn't go through earlier. I though I had added them already.

**Comment by Atif-Anwer** [comment]
I've uploaded the weights also! Hope it helps!

**Comment by watertianyi** [comment]
@Atif-Anwer Assuming that opencv=python is used to read images for prediction, how to use opencv to read data and display the results?
 src_img = cv2.imread(img_path)
gray_img = cv2.cvtColor(src_img,cv2.COLOR_BGR2GRAY)
print(gray_img.shape)
mat_img = np.expand_dims(gray_img, axis=0)
result = model.predict( mat_img)
result = np.asarray(result[0, :, :, :],dtype=np.uint8)
print(result.shape)
res=np.hstack([gray_img])
cv_show('pred',res)
cv_show("res",result)

**Comment by Atif-Anwer** [comment]
The entire process is done in the jupyter notebook. Its the same for a local python script also. You can look at that for reference.
